---
title: "[Re] Drivers of evapotranspiration from boreal wildfires"
author: "Ben Bond-Lamberty"
date: "`r format(Sys.time(), '%d %B %Y')`"
bibliography: bibliography.bib
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Abstract

Computational reproducibility is a difficult challenge across science. I attempted to use R 3.6.1 to reproduce linear model fits, done originally using v2.6.0 for a 2009 paper on the drivers of large-scale forest evapotranspiration after wildfire. Model outputs were largely identical, aside from minor formatting changes, except for one--out of 12 total--regression in which the median residual value changed very slightly (in the sixth decimal place). I suggest that this essentially successful reproducibility is due to the relative simplicity of the script, its use of only base R functions, and R's historically conservative approach to breaking changes.

### Introduction

Significant changes in forest fires have occurred in recent decades in the global boreal (high latitude) forest, but the effects of changing climate and disturbance on evapotranspiration (ET) and forest water cycling more generally are not well understood. In a previous study [@Bond-Lamberty2007-uq] we had explored the ecological and carbon-cycle consequences of changes in the fire regime using an ecosystem model run at high resolution across a large (1000 km x 1000 km) area of the central Canadian boreal forest. In a subsequent paper [@Bond-Lamberty2009-py], we used the same model outputs to examine the _hydrological_ implications of these wildfire regime shifts [@Nolan2014-us].

How reproducible are the results reported in Bond-Lamberty et al. [-@Bond-Lamberty2009-py]? The article manuscript was written in 2007-2008, initially submitted in April 2008, and a final, revised version was submitted in October of that year. The system timestamp on the script output file is 2008-03-16. The methods section reports that R 2.6.0 [@R_Core_Team2007-eq], which was released on 2007-10-03, was used for all analyses. The source code was not publicly archived, but retained in the lead author's personal records; it has no license. The original hardware would have been an Apple laptop (probably a 2006-2007 MacBook Pro). As noted above, the code file was archived by the lead author, and so was easy for him (but no one else) to find. The code has no comments or instructions.

### Methods

_Retrieval of the software_

The source code being reproduced here is short and was written to analyze relationships between various potential driving factors and three output variables of interest: ET, canopy evaporation, and canopy transpiration, all annual flux totals over the 1948-2005 model run period. The code simply reads in a comma-separated data file holding the modeling outputs, prints a summary of the data, and then fits and prints 12 separate regressions (three output variables times four possible independent variables). These fit statistics were reported on p. 1247 of Bond-Lamberty et al. [-@Bond-Lamberty2009-py].

_Execution_

Because the code uses only base R functions, it has no dependencies other than a standard R installation. Both in 2007-2008 and 2020, the default Mac R installer provided by CRAN was used to install R (i.e. it was not built from source). The code was re-run, without modification, on a 2018 MacBook Pro under R version 3.6.1 (2019-07-05) [@R_Core_Team2019-eq]; platform: x86_64-apple-darwin15.6.0 (64-bit); running under macOS Mojave 10.14.6. Its output was then compared with the printed output from the 2007-2008 R 2.6.0 code, which had been recorded via R's `sink()` function and archived with the code.

### Results and discussion

Setting aside minor spacing and text capitalization changes, only one numerical change occurred, albeit in the sixth decimal place. In the 2008 R 2.6.0 output of a linear regression between canopy evaporation (dependent variable) and precipitation (independent), the residuals were given as:
```
Residuals:
      Min        1Q    Median        3Q       Max 
-0.028858 -0.009186  0.002088  0.010753  0.019997 
```
In the 2020 R 3.6.0 output, this output line (specifically, the "Median" value) was:
```
Residuals:
      Min        1Q    Median        3Q       Max 
-0.028858 -0.009186  0.002089  0.010753  0.019997 
```
In addition, in two cases p-values were reported with a different number of significant digits in the 2020 output: once gaining a digit ("0.005451" in 2020 versus "0.00545" in 2008) and once losing one ("0.000103" and 0.0001030" respectively). No other numerical differences occurred.

Whether these minor differences were due to the different R version, or different underlying operating system and/or libraries, is uncertain. R version 2.6.0 (https://cran.r-project.org/bin/macosx/old/R-2.6.0.dmg) is unfortunately not installable under modern versions of macOS. Instead I downloaded R 2.6.0 for Windows (`i386-pc-mingw32`) and ran the code on it; the printed results were identical to the 2007-2008 output file. This suggests that the minor differences noted above between the R 2.6.0 and 3.6.0 outputs were due to changes in R itself, not differences in the underlying systems.

As simple as the code and this reproducibility exercise was, there are some interesting notes that can be drawn from it. Reproducibility has been a well-supported (see e.g. https://cran.r-project.org/web/views/ReproducibleResearch.html) core value of the R Core Team and larger communnity, and the base version of the software has been highly stable over the last twenty years since version 1.0. Specifically with regard to this exercise, the core of the `lm` (linear model) source code, found at https://svn.r-project.org/R/trunk/src/library/stats/R/lm.R, has changed little over the last decade. Refinements and extensions to R's linear modeling capabilities have instead come from contributed packages [e.g. @Gromping2006-hr].

In contrast, many of the most highly used R packages, for example those of the popular tidyverse ecosystem [@Wickham2019-gd] have historically changed their behavior and syntax much more frequently. This allows for faster evolution and cleaner, consistent syntax (not among base R's strong points) but poses greater challenges for stable and reproducible software. For example, the popular `dplyr` package lists (see https://github.com/tidyverse/dplyr/blob/master/NEWS.md) breaking changes introduced at versions 0.5, 0.7, 0.7.5, 0.8, 0.8.1, and 1.0, over a timespan of four years; it seems unlikely that code taking advantage of its powerful features and speed would be reproducible without being tweaked or rewritten. This highlights some of the challenges surrounding computational reproducibility [@Thornton2005-hw; @Lowndes2017-el], in particular balancing reproducibility with other potentially important criteria such as performance or confidentiality [@Stodden2014-dy; @Peng2011-jw].

### Conclusions

There were many potential limitations in reproducing even this very short analysis script over ten years later: the code contained no documentation about R or package versions, nor information about the hardware information it was originally run on. The analysis date could only be reconstructed from the output file timestamp (luckily unaltered). Saving this output file, however, at least allowed for a robust check on the reproducibility of the analysis, script, and underlying R software after 12 years. The essentially successful result is due to the relative simplicity of the script, its use of only base R functions, and R's conservative approach to breaking changes.

### References
